export enum UpdateStatus {
  UPDATE_AVAILABLE = "UPDATE_AVAILABLE",
  UPDATE_DOWNLOADING = "UPDATE_DOWNLOADING",
  UPDATE_CHECKING = "UPDATE_CHECKING",
  UPDATE_IDLE = "UPDATE_IDLE",
  UPDATE_NEEDS_REBOOT = "UPDATE_NEEDS_REBOOT",
  UPDATE_FINALIZING = "UPDATE_FINALIZING",
  UPDATE_ERROR = "UPDATE_ERROR"
}
